version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    working_directory: ~/app

    steps:
      - checkout
      - run:
          command: ./gradlew build
